- name: "Install git"
  apt: name=git

- name: "checkout project"
  git: repo=http://username:password@git.svc.ft.com/scm/ftnet/network_applications.git
       dest=/tmp/1
       accept_hostkey=yes
       force=yes
